Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Model;
using WebApplication2.Data.Repository;
using WebApplication2.Interfaces;
using WebApplication2.ViewModels;

namespace WebApplication2.Controllers
{
    public class ShopCartController: Controller
    {
        private readonly IAllBicucle  _allBicucle;
        private readonly ShopCart  _shopCart;
        public ShopCartController(IAllBicucle allBicucle, ShopCart shopCart )

        {
            _allBicucle = allBicucle;
            _shopCart = shopCart;

        }

        public ViewResult Index()
        {
            var item = _shopCart.GetShopItems();
            _shopCart.shopCartItems = item;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }
        public RedirectToActionResult addToCaret(int id)
        {
            var item = _allBicucle.Bicycles.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
              //  item.count -= 1;
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult removeToCaret(int id,int idod)
        {
            var item = _allBicucle.Bicycles.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                //  item.count -= 1;
                _shopCart.RemoveFCart(item,idod);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/AllBicycle.cshtml
@model Bicycle

<div class="col-lg-4">
    <img class="img-thumbnail" src=@Model.img />
    <h2>Велосипед @Model.name</h2>
    <p>Цена:@Model.price.ToString("# руб")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCaret" asp-route-id="@Model.id">Добавить в корзину</a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" 
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    

</head>

<body>
    <header>
        <nav>
            <ul>
                <li><a href="/">Главная</a></li>
                <li>
                    <a href="">Категории</a>
                    <ul>
                        <li><a href="/Bicycle/List/mountain">Горные</a></li>
                        <li><a href="/Bicycle/List/city">Городские</a></li>
                        <li><a href="/Bicycle/List/folding">Складные</a></li>
                        <li><a href="/Bicycle/List/baby">Детские</a></li>
                        <li><a href="/Bicycle/List/racing">Гоночные</a></li>
                    </ul>
                </li>
                <li><a href="/ShopCart/">Корзина</a></li>
           
                <li>@Html.ActionLink(linkText: "LogIn", actionName: "Login", controllerName: "Account")</li>
            </ul>
        </nav>
    </header>
    <div class="container mt-3">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" 
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    

</head>

<body>
    <header>
        <nav>
           Панель администратора
        </nav>
    </header>
    <div class="container mt-3">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>