Controllers/AddBicycleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data.Model;
using WebApplication2.Interfaces;
using WebApplication2.ViewModels;

namespace WebApplication2.Controllers
{
    [Area("Admin")]
    public class AddBicycleController : Controller
    {
        private readonly IBicycleCategory bicycleCategory;
        private readonly IAllBicucle allBicucle;

        public AddBicycleController(IBicycleCategory category, IAllBicucle allBicucle)
        {
            this.allBicucle = allBicucle;
            bicycleCategory = category;
        }
        public ActionResult Index()

        {
            IEnumerable<Bicycle> bicycles = allBicucle.Bicycles.OrderBy(i => i.categoryId);
            var bicObj = new BicycleListViewModel
            {
                allBicycles = bicycles
            };
        
            return View(bicObj);
        }

        public ActionResult Create()
        {
            Bicycle bicycleListViewModel = new Bicycle();
            bicycleListViewModel.listOfType = (from obj in bicycleCategory.AllCategories
                                               select new SelectListItem()
                                               {
                                                   Text = obj.categName,
                                                   Value = obj.id.ToString()
                                               }).ToList();
            return View(bicycleListViewModel);
        }
        [HttpPost]
          public ActionResult Create(Bicycle bicycle)
        {
            if (ModelState.IsValid)
            {
                allBicucle.createBicycle(bicycle);
              
            }
            return RedirectToAction("Complete");
        }
        public RedirectToActionResult RemoveBicycle(int id)
        {
            var item = allBicucle.Bicycles.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                //  item.count -= 1;
               allBicucle.RemoveBicycle(item);
            }
            return RedirectToAction("Complete");
        }
        public IActionResult Complete()
        {

            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }

    }
}

Areas/Admin/Views/AddBicycle/Complete.cshtml
<h3>@ViewBag.Message</h3>

Areas/Admin/Views/AddBicycle/Create.cshtml
@model Bicycle

<div class="row mb-5">
    <h3>Добавить велосипед</h3>
    <form asp-action="Create" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>

            <div class="col-12">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="shortDesc"></label>

            <div class="col-12">
                <input asp-for="shortDesc" class="form-control" />
                <span asp-validation-for="shortDesc" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="count"></label>

            <div class="col-12">
                <input asp-for="count" class="form-control" />
                <span asp-validation-for="count" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="price"></label>

            <div class="col-12">
                <input asp-for="price" class="form-control" />
                <span asp-validation-for="price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="firm"></label>

            <div class="col-12">
                <input asp-for="firm" class="form-control" />
                <span asp-validation-for="firm" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="categoryId"></label>

            <div class="col-12">

                <select asp-for="categoryId" asp-items="@Model.listOfType"></select>
                <span asp-validation-for="categoryId" class="text-danger"></span>

            </div>
        </div>

<input class="btn btn-success mt-5 " type="submit" value="Завершить заказ" />
    </form>

</div>

Areas/Admin/Views/AddBicycle/Index.cshtml
<table border="1" cellpadding="5">
    <thead>
        <tr>
            <th>
                Название
            </th>
            <th>
                Категория
            </th>
            <th>
                Цена
            </th>
            <th>
                Количество
            </th>
            <th>
                Фирма
            </th>
            <th>
                Изображение
            </th>

        </tr>




    <tbody>
        @{
            foreach (Bicycle bicycle in Model.allBicycles)
            {

                <tr>
                    <td>@bicycle.name</td>

                    <td>@bicycle.Category.categName</td>
                    <td>@bicycle.price</td>

                    <td>@bicycle.count</td>

                    <td>@bicycle.firm</td>

                    <td><img src="@bicycle.img" width="40" /></td>

                    <p><a class="btn btn-warning" asp-controller="AddBicycle" asp-action="RemoveBicycle" asp-route-id="@bicycle.id">Удалить</a></p>
                </tr>



            }

        }
    </tbody>
    </thead>
</table>

<a class="btn btn-danger" asp-controller="AddBicycle" asp-action="Create">Добавить велосипед</a>