Areas/Admin/Controllers/ShowOrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Interfaces;
using WebApplication2.ViewModels;

namespace WebApplication2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ShowOrderController : Controller
    {
        IAllOrders allOrders;
        IAllBicucle allBicucle;
        public ShowOrderController(IAllOrders allOrders, IAllBicucle allBicucle)
        {
            this.allOrders = allOrders;
            this.allBicucle = allBicucle;
        }
        public ViewResult Index()
        {
            OrderViewModel orderViewModel = new OrderViewModel
            {
                order = allOrders.Order,
                bicycles = allBicucle.getBicycles
                
            };
        foreach(var a in orderViewModel.order)
            {
                a.orderDetails = allOrders.orderDetails.Where(k => k.orderId == a.id).ToList();
            }
            return View(orderViewModel);
        }
        public IActionResult RemoveOrder(int id)
        {
            var item = allOrders.Order.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                item.orderDetails = allOrders.orderDetails.Where(k => k.orderId == item.id).ToList();
                //  item.count -= 1;
                allOrders.removeOrder(item, item.orderDetails);
            }
            return RedirectToAction("Complete");
        }
        public IActionResult Complete()
        {

            ViewBag.Message = "Заказ успешно обработан";
            return View();
        }

    }
}

Areas/Admin/Views/ShowOrder/Complete.cshtml
<h3>@ViewBag.Message</h3>

Areas/Admin/Views/ShowOrder/Index.cshtml
@model OrderViewModel

<table border="1" cellpadding="5">
    <thead>
        <tr>
            <th>
                Имя
            </th>
            <th>
                Фамилия
            </th>
            <th>
                Отчество
            </th>
            <th>
                Телофон
            </th>
            <th>
                Адрес
            </th>
            <th>
                Email
            </th>
            <th>
                Заказ
            </th>

        </tr>




    <tbody>
        @{
            foreach (var order in Model.order)
            {

                <tr>
                    <td>@order.Name</td>

                    <td>@order.Surname</td>
                    <td>@order.Patronic</td>

                    <td>@order.phone</td>

                    <td>@order.adress</td>

                    <td>@order.email</td>
                    @foreach (var a in order.orderDetails)
                    {

                        @foreach (var k in Model.bicycles.Where(i => a.bicycleId == i.id).ToList())
                        {
                            <td>
                    @k.name
                            </td>

                        }

                    }

                <td>  <p><a class="btn btn-warning" asp-controller="ShowOrder" asp-action="RemoveOrder" asp-route-id="@order.id">Удалить</a></p></td>
                </tr>



            }

        }
    </tbody>
    </thead>
</table>